theme: jekyll-theme-cayman
name: Alex Schittko
title: The world through my eyes
description: Just a developer who goes to school
avatar: https://avatars.githubusercontent.com/u/7796475?s=460&v=4
github_username: alex4108

plugins:
  - jekyll-feed