theme: jekyll-theme-architect
name: Alex Schittko
description: Just a developer in training
avatar: https://avatars.githubusercontent.com/u/7796475?s=460&v=4
github_username: alex4108

plugins:
  - jekyll-feed